'use client'

export { AssistantMessage } from './AssistantMessage'
export type { AssistantMessageProps } from './AssistantMessage'
export { UserMessage } from './UserMessage'
export type { UserMessageProps } from './UserMessage'
export { Messages } from './Messages'
export type { MessagesProps } from './Messages'
export { Input } from './Input'
export type { InputProps } from './Input'
export { RenderTextMessage } from './RenderTextMessage'
export type { RenderTextMessageProps } from './RenderTextMessage'
export { RenderActionExecutionMessage } from './RenderActionExecutionMessage'
export type { RenderActionExecutionMessageProps } from './RenderActionExecutionMessage'
export { RenderAgentStateMessage } from './RenderAgentStateMessage'
export type { RenderAgentStateMessageProps } from './RenderAgentStateMessage'
export { RenderResultMessage } from './RenderResultMessage'
export type { RenderResultMessageProps } from './RenderResultMessage'
export { RenderMessage } from './RenderMessage'
export type { RenderMessageProps } from './RenderMessage'
export { Window } from './Window'
export type { WindowProps } from './Window'
export { Button } from './Button'
export type { ButtonProps } from './Button'
export { Header } from './Header'
export type { HeaderProps } from './Header'

import { AssistantMessage } from './AssistantMessage'
import { UserMessage } from './UserMessage'
import { Messages } from './Messages'
import { Input } from './Input'
import { RenderMessage } from './RenderMessage'
import { Window } from './Window'
import { Button } from './Button'
import { Header } from './Header'

/** Spread onto CopilotChat, CopilotPopup or CopilotSidebar (v1 slot API). */
export const copilotKitComponents = { AssistantMessage, UserMessage, Messages, Input, RenderMessage, Window, Button, Header, className: 'm3e-agui-ck-chat' }
